### ISSUE TITLE
6.x versions gone from jitpack?

### ISSUE THREAD

**Issue by savvasdalkitsis** [MFlisar/Lumberjack#20]
Were old versions removed from jitpack? My project started failing to build suddenly and updating to 7.x, while not difficult, is API breaking

**Comment by savvasdalkitsis** [comment]
Turns out github was having a hiccup

**Comment by MFlisar** [comment]
FYI: jitpack is the problem. it looses builds and then it has to rebuild the project... the problem is, that default values in jitpacks config changes over the time, so sometimes, its not possible to rebuild an old project if the project has not defined everything necessary manually...

That's why I moved on to maven with all my projects.
